"""Neural-network position evaluator (PyTorch).

Implements the ``Evaluator`` protocol from ``chess_project.core.types``.

Architecture (NNUE-lite):
    768 sparse inputs  →  256 (CReLU)  →  32 (ReLU)  →  1 (tanh → scale)

    Input encoding: 12 piece-type planes × 64 squares, binary.
    Output: centipawns (int), positive = white advantage.

The network is small enough to train on a single 3080 in 1-3 hours
on ~2-5 M positions generated by the existing HCE via self-play.

Quick-start
-----------
Generate data + train::

    python -m chess_project.engine.ml_evaluator generate --n 2000000
    python -m chess_project.engine.ml_evaluator train --epochs 10

Then use in your engine::

    from chess_project.engine.ml_evaluator import NNEvaluator
    evaluator = NNEvaluator("model.pt")
    score = evaluator.evaluate(position)
"""

from __future__ import annotations

import argparse
import math
import os
import struct
import sys
import time
from pathlib import Path
from typing import Final

import torch
import torch.nn as nn
from torch import Tensor

from chess_project.core.types import Color, piece_color, piece_type_of
from chess_project.core.position import Position

# ---------------------------------------------------------------------------
# Feature extraction: Position → 768-dim sparse binary vector
# ---------------------------------------------------------------------------
# Piece codes in your engine:
#   White: PAWN=1 KNIGHT=2 BISHOP=3 ROOK=4 QUEEN=5 KING=6
#   Black: PAWN=9 KNIGHT=10 BISHOP=11 ROOK=12 QUEEN=13 KING=14
#
# Feature index = piece_index(0..11) * 64 + square
# piece_index: WP=0 WN=1 WB=2 WR=3 WQ=4 WK=5 BP=6 BN=7 BB=8 BR=9 BQ=10 BK=11

# Map piece code → feature-plane index (0-11), -1 for empty
_PIECE_TO_PLANE: Final[list[int]] = [
    -1,         # 0  empty
     0, 1, 2, 3, 4, 5,  # 1-6   white P N B R Q K
    -1, -1,     # 7-8  unused
     6, 7, 8, 9, 10, 11, # 9-14  black P N B R Q K
]

NUM_FEATURES: Final[int] = 12 * 64  # 768


def position_to_features(pos: Position) -> list[int]:
    """Return list of active feature indices (sparse)."""
    indices: list[int] = []
    for sq in range(64):
        pc = pos.board[sq]
        if pc:
            plane = _PIECE_TO_PLANE[pc]
            indices.append(plane * 64 + sq)
    return indices


def position_to_tensor(pos: Position, device: torch.device | None = None) -> Tensor:
    """Convert a single Position to a dense [1, 768] float tensor."""
    t = torch.zeros(1, NUM_FEATURES, device=device)
    for idx in position_to_features(pos):
        t[0, idx] = 1.0
    return t


def positions_to_batch(
    positions: list[Position], device: torch.device | None = None,
) -> Tensor:
    """Convert N positions to a [N, 768] float tensor."""
    batch = torch.zeros(len(positions), NUM_FEATURES, device=device)
    for i, pos in enumerate(positions):
        for idx in position_to_features(pos):
            batch[i, idx] = 1.0
    return batch


# ---------------------------------------------------------------------------
# Network
# ---------------------------------------------------------------------------

class ChessNet(nn.Module):
    """Tiny NNUE-style network.

    768 → 256 (clipped-ReLU) → 32 (ReLU) → 1 (tanh, scaled)

    Output is in the range (-1, 1).  The wrapper scales it to centipawns.
    """

    def __init__(self) -> None:
        super().__init__()
        self.fc1 = nn.Linear(NUM_FEATURES, 256)
        self.fc2 = nn.Linear(256, 32)
        self.fc3 = nn.Linear(32, 1)

    def forward(self, x: Tensor) -> Tensor:
        x = torch.clamp(self.fc1(x), 0.0, 1.0)  # CReLU / clipped ReLU
        x = torch.relu(self.fc2(x))
        x = torch.tanh(self.fc3(x))  # output ∈ (-1, 1)
        return x


# ---------------------------------------------------------------------------
# Evaluator protocol implementation
# ---------------------------------------------------------------------------

# Scale factor: tanh output of ±1 maps to ±MAX_CP centipawns.
# 800 cp ≈ decisive advantage; beyond that the curve saturates,
# which is fine — checkmate scores are handled by the search, not the eval.
_MAX_CP: Final[int] = 800


class NNEvaluator:
    """Implements ``Evaluator.evaluate(position) -> int``.

    Args:
        model_path: Path to a saved ``ChessNet`` state-dict (``.pt`` file).
        device:     ``"cpu"`` or ``"cuda"``.  Default auto-detects.
    """

    __slots__ = ("_net", "_device")

    def __init__(
        self,
        model_path: str | Path = "model.pt",
        device: str | None = None,
    ) -> None:
        self._device = torch.device(
            device or ("cuda" if torch.cuda.is_available() else "cpu")
        )
        self._net = ChessNet()
        self._net.load_state_dict(
            torch.load(model_path, map_location=self._device, weights_only=True)
        )
        self._net.to(self._device)
        self._net.eval()

    def evaluate(self, position: object) -> int:
        """Return score in centipawns, positive = white advantage."""
        pos: Position = position  # type: ignore[assignment]
        with torch.no_grad():
            inp = position_to_tensor(pos, self._device)
            out: float = self._net(inp).item()
        return int(out * _MAX_CP)


# =========================================================================
# Training utilities  (run via  python -m chess_project.engine.ml_evaluator)
# =========================================================================

# Binary data format for training samples:
#   Each sample = 64 bytes (board) + 1 byte (turn) + 2 bytes (score, int16)
#   Total: 67 bytes per sample, compact and fast to load.
_SAMPLE_FMT = "64B B h"  # struct format
_SAMPLE_SIZE = struct.calcsize(_SAMPLE_FMT)  # 67 bytes


def _write_sample(f, pos: Position, score: int) -> None:
    """Write one training sample to a binary file."""
    clamped = max(-_MAX_CP, min(_MAX_CP, score))
    f.write(struct.pack(
        _SAMPLE_FMT,
        *pos.board,
        int(pos.turn),
        clamped,
    ))


def _read_samples(path: Path, device: torch.device) -> tuple[Tensor, Tensor]:
    """Read all samples from binary file into tensors."""
    data = path.read_bytes()
    n = len(data) // _SAMPLE_SIZE
    print(f"Loading {n:,} samples from {path}")

    features = torch.zeros(n, NUM_FEATURES)
    scores = torch.zeros(n, 1)

    for i in range(n):
        offset = i * _SAMPLE_SIZE
        values = struct.unpack_from(_SAMPLE_FMT, data, offset)
        board = values[:64]
        turn = values[64]
        score = values[65]

        for sq in range(64):
            pc = board[sq]
            if pc:
                plane = _PIECE_TO_PLANE[pc]
                features[i, plane * 64 + sq] = 1.0

        scores[i, 0] = score / _MAX_CP  # normalise to (-1, 1)

    return features.to(device), scores.to(device)


# ---------------------------------------------------------------------------
# Data generation via self-play with existing HCE
# ---------------------------------------------------------------------------

def download_lichess_data(out_path: Path, num_samples: int) -> None:
    """Download labelled positions from the Lichess HuggingFace dataset.

    Requires: ``pip install datasets``

    Source: https://huggingface.co/datasets/Lichess/chess-position-evaluations
    Each row has ``fen`` (str) and ``cp`` (int, centipawns from Stockfish).
    Rows with mate scores (``cp`` is None) are skipped.
    """
    from datasets import load_dataset  # type: ignore[import-untyped]
    from chess_project.io.fen import parse_fen

    print(f"Streaming Lichess dataset -- collecting {num_samples:,} positions ...")
    ds = load_dataset(
        "Lichess/chess-position-evaluations",
        split="train",
        streaming=True,
    )

    collected = 0
    skipped = 0
    t0 = time.time()

    with open(out_path, "wb") as f:
        for row in ds:
            if collected >= num_samples:
                break

            cp = row.get("cp")
            fen = row.get("fen")
            if cp is None or fen is None:
                skipped += 1
                continue

            try:
                pos = parse_fen(fen)
            except (ValueError, IndexError):
                skipped += 1
                continue

            _write_sample(f, pos, int(cp))
            collected += 1

            if collected % 50_000 == 0:
                elapsed = time.time() - t0
                rate = collected / elapsed if elapsed > 0 else 0
                print(
                    f"  {collected:>9,} / {num_samples:,}  "
                    f"({skipped} skipped, {rate:.0f} pos/s)"
                )

    elapsed = time.time() - t0
    print(
        f"Done: {collected:,} samples ({skipped} skipped) "
        f"in {elapsed:.0f}s -> {out_path}"
    )


def generate_data(out_path: Path, num_samples: int, search_depth: int = 4) -> None:
    """Play random-ish games using AlphaBetaSearch and record labelled positions.

    Strategy: play games using AlphaBetaSearch at low depth with the HCE.
    After each move, record the position and the HCE static eval as the label.
    Add randomisation by playing a random move with 20% probability
    in the first 10 plies to get position diversity.
    """
    import random as rng
    from chess_project.engine.evaluator import evaluate as hce_evaluate
    from chess_project.engine.search import AlphaBetaSearch
    from chess_project.engine.ordering import MvvLvaOrderer
    from chess_project.core.rules import Game

    engine = AlphaBetaSearch(orderer=MvvLvaOrderer(), max_depth=search_depth)
    collected = 0
    games_played = 0

    with open(out_path, "wb") as f:
        while collected < num_samples:
            game = Game()
            ply = 0
            games_played += 1

            while not game.is_game_over() and ply < 300:
                legal = game.legal_moves()
                if not legal:
                    break

                # Opening randomisation: 20% random move in first 10 plies
                if ply < 10 and rng.random() < 0.20:
                    move = rng.choice(legal)
                else:
                    move = engine.choose_move(
                        game.position, depth=search_depth, time_ms=500,
                    )

                game.push(move)
                ply += 1

                # Record position after the move (skip very early positions)
                if ply >= 6 and collected < num_samples:
                    score = hce_evaluate(game.position)
                    _write_sample(f, game.position, score)
                    collected += 1

                    if collected % 10_000 == 0:
                        elapsed = time.time() - _gen_start
                        rate = collected / elapsed if elapsed > 0 else 0
                        print(
                            f"  {collected:>9,} / {num_samples:,}  "
                            f"({games_played} games, {rate:.0f} pos/s)"
                        )

    print(f"Done: {collected:,} samples in {games_played} games -> {out_path}")


# ---------------------------------------------------------------------------
# Training loop
# ---------------------------------------------------------------------------

def train(
    data_path: Path,
    model_path: Path,
    epochs: int = 10,
    batch_size: int = 4096,
    lr: float = 1e-3,
) -> None:
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    print(f"Device: {device}")

    features, targets = _read_samples(data_path, device)
    n = features.shape[0]

    net = ChessNet().to(device)
    optimiser = torch.optim.Adam(net.parameters(), lr=lr)
    scheduler = torch.optim.lr_scheduler.StepLR(optimiser, step_size=3, gamma=0.5)
    loss_fn = nn.MSELoss()

    print(f"Training {sum(p.numel() for p in net.parameters()):,} parameters")
    print(f"Samples: {n:,}  Batch size: {batch_size}  Epochs: {epochs}")

    for epoch in range(1, epochs + 1):
        # Shuffle
        perm = torch.randperm(n, device=device)
        features = features[perm]
        targets = targets[perm]

        total_loss = 0.0
        batches = 0
        t0 = time.time()

        for start in range(0, n, batch_size):
            end = min(start + batch_size, n)
            x = features[start:end]
            y = targets[start:end]

            pred = net(x)
            loss = loss_fn(pred, y)

            optimiser.zero_grad()
            loss.backward()
            optimiser.step()

            total_loss += loss.item()
            batches += 1

        scheduler.step()
        avg_loss = total_loss / batches
        elapsed = time.time() - t0
        # Convert MSE on tanh-scaled output back to centipawn RMSE
        cp_rmse = math.sqrt(avg_loss) * _MAX_CP
        print(
            f"  Epoch {epoch:>2}/{epochs}  "
            f"loss={avg_loss:.6f}  RMSE~{cp_rmse:.0f}cp  "
            f"lr={scheduler.get_last_lr()[0]:.1e}  {elapsed:.1f}s"
        )

    torch.save(net.state_dict(), model_path)
    print(f"Model saved -> {model_path}")


# ---------------------------------------------------------------------------
# CLI entry point
# ---------------------------------------------------------------------------

_gen_start: float = 0.0  # module-level for progress callback


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Train a neural chess evaluator",
    )
    sub = parser.add_subparsers(dest="command")

    dl = sub.add_parser("download", help="Download Lichess Stockfish-labelled data (recommended)")
    dl.add_argument("--n", type=int, default=2_000_000, help="Number of positions")
    dl.add_argument("--out", type=str, default="train_data.bin", help="Output file")

    gen = sub.add_parser("generate", help="Generate training data via self-play (slow fallback)")
    gen.add_argument("--n", type=int, default=2_000_000, help="Number of positions")
    gen.add_argument("--depth", type=int, default=4, help="HCE search depth")
    gen.add_argument("--out", type=str, default="train_data.bin", help="Output file")

    tr = sub.add_parser("train", help="Train the network")
    tr.add_argument("--data", type=str, default="train_data.bin", help="Training data")
    tr.add_argument("--model", type=str, default="model.pt", help="Output model path")
    tr.add_argument("--epochs", type=int, default=10)
    tr.add_argument("--batch-size", type=int, default=4096)
    tr.add_argument("--lr", type=float, default=1e-3)

    args = parser.parse_args()

    if args.command == "download":
        download_lichess_data(Path(args.out), args.n)
    elif args.command == "generate":
        global _gen_start
        _gen_start = time.time()
        generate_data(Path(args.out), args.n, args.depth)
    elif args.command == "train":
        train(Path(args.data), Path(args.model), args.epochs, args.batch_size, args.lr)
    else:
        parser.print_help()


if __name__ == "__main__":
    main()
